language: cpp

arch:
  - amd64
  - arm64               # For raspberry

addons:
  apt:
    update: true        # Run apt update
    packages:           # Apt install dependencies
      - build-essential
      - bison
      - flex

script:                 # Run build and run script
  - make clean build
  - make clean run