language: cpp

arch:
  - amd64
  - arm64

addons:
  apt:
    update: true
    packages:
      - build-essential
      - bison
      - flex
      - libsfml-dev

script:
  - make clean spikes # Assume that the spikes runs
  - make clean build # Assume that the program build
  # sfml issues - make clean auto # Assume that the program is running with the examples
