language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential

install:
  - sudo apt-get install -y bison
  - sudo apt-get install -y flex

script:
  - make clean run